### ISSUE TITLE
Autocomplete crashes 

### ISSUE THREAD

**Issue by Joker84a** [telerik/nativescript-ui-feedback#1008]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
_I have installed auto-complete ui plugin by tns command. It is showed properly but when I type a letter which is inside the item suggested, it returns me this error _

### Which platform(s) does your issue occur on?
_Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** latest 
- **CLI:**5.1.1
- **Cross-platform modules:**  5.1.0,
-@angular-devkit/core         7.1.4
-@angular-devkit/schematics   7.1.4
-@ngtools/webpack             7.1.4
-@schematics/angular          7.1.4
-nativescript: 		     5.1.1
-rxjs                         6.3.3
-typescript                   3.1.6
-webpack                      4.27.1

- **Runtime(s):**  5.1.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application try to type some word which is inside the suggested items and it crashes
2. I got this error:
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateViewHolder failed

Error: Expecting a valid View instance.
File: "file:///data/data/org.nativescript.myangularapp2/files/app/vendor.js, line: 109080, column: 12

StackTrace: 
	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.myangularapp2/files/app/vendor.js', line: 78818, column: 33
	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._addView', file:'file:///data/data/org.nativescript.myangularapp2/files/app/vendor.js', line: 109080, column: 19
	Frame: function:'push.../node_modules/tns-core-modules/ui/layouts/layout-base-common.js.LayoutBaseCommon.addChild', file:'file:///data/data/org.nativescript.myangularapp2/files/app/vendor.js', line: 117415, column: 14
	Frame: function:'AutoCompleteAdapter.onCreateViewHolder', file:'file:///data/data/org.nativescript.myangularapp2/files/app/vendor.js', line: 80484, column: 24


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
	at com.tns.Runtime.callJSMethod(Runtime.java:987)
	at com.tns.Runtime.callJSMethod(Runtime.java:967)
	at com.tns.Runtime.callJSMethod(Runtime.java:959)
	at com.tns.gen.com.telerik.widget.autocomplete.AutoCompleteAdapter_vendor_80474_32_AutoCompleteAdapter.onCreateViewHolder(AutoCompleteAdapter_vendor_80474_32_AutoCompleteAdapter.java:23)
	at com.tns.gen.com.telerik.widget.autocomplete.AutoCompleteAdapter_vendor_80474_32_AutoCompleteAdapter.onCreateViewHolder(AutoCompleteAdapter_vendor_80474_32_AutoCompleteAdapter.java:8)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:19659)
	at android.view.ViewGroup.layout(ViewGroup.java:6075)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_ just used the angular code from this link : http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/AutoCompleteTextView/display-modes_

**Comment by tsonevn** [comment]
Hi @Joker84a,
I tested the `AutoCompleteTextView` component in a sample project, however, was unable to recreate the problem. Check out the test project [here](https://play.nativescript.org/?template=play-ng&id=C0IzMW). I would suggest to clear up your project and try to rebuild it.
1. delete `node_modules`, `platforms`, `hooks` folders and `package-lock.json` file
2. run `npm i`
3. rebuild the project `tns run <platform_name>`

**Comment by elena-p** [comment]
closing due to inactivity
