### ISSUE TITLE
[RadDataForm] Android: IllegalStateException when navigating to a read only property

### ISSUE THREAD

**Issue by rklde** [telerik/nativescript-ui-feedback#1109]
### Tell us about the problem
On Android 9, when navigating with the Keyboard next Button and the property navigated to is read only, a IllegalStateException is thrown.

System.err: java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
System.err: 	at android.widget.TextView.onKeyUp(TextView.java:7799)
System.err: 	at android.view.KeyEvent.dispatch(KeyEvent.java:2716)
System.err: 	at android.view.View.dispatchKeyEvent(View.java:12450)
System.err: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
System.err: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
System.err: 	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:389)
System.err: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
System.err: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
System.err: 	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:389)
System.err: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
System.err: 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
System.err: 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:428)
System.err: 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
System.err: 	at android.app.Activity.dispatchKeyEvent(Activity.java:3360)
System.err: 	at android.support.v4.app.SupportActivity.superDispatchKeyEvent(ComponentActivity.java:108)
System.err: 	at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
System.err: 	at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
System.err: 	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
System.err: 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
System.err: 	at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
System.err: 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5037)
System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4905)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
System.err: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
System.err: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
System.err: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
System.err: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
System.err: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
System.err: 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4203)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Which platform(s) does your issue occur on?
Android 9 (API 28). It works fine on API lower 28

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI plugin version:** (the version of nativescript-ui-* in the `package.json`)

    "nativescript-ui-autocomplete": "^4.0.0",
    "nativescript-ui-dataform": "^4.0.0",
    "nativescript-ui-listview": "^6.3.0",
    "nativescript-ui-sidedrawer": "^6.0.0",

- **CLI:** (run `tns --version` to fetch it)
5.3.4

- **Cross-platform modules:** (the version of tns-core-modules in the `package.json`)
"tns-core-modules": "^5.3.2"

- **Runtime(s):** (the `"tns-android"` and `"tns-ios"` properties in the `package.json`)
    "tns-android": {
      "version": "5.3.1"
    }

### Please tell us how to recreate the issue in as much detail as possible.
I have several groups in a Dataform. I'm using a Gridlayout in the dataform and set the columnindex and index to order them.
Some properties have the read only property set to true. When using the "Next" Button on the Android Key board of a property before the readonly property the exception is thrown. 

                                 <df:PropertyGroup.properties>
                                        <df:EntityProperty name="kronendurchmesser" displayName="Kronendurchmesser (in m, eine Nachkommasstelle)" columnIndex="0" index="4">
                                            <df:EntityProperty.editor>
                                                <df:PropertyEditor type="Decimal"/>
                                            </df:EntityProperty.editor>
                                        </df:EntityProperty>
                                        <df:EntityProperty name="hoehe" displayName="Höhe" columnIndex="1" index="4">
                                            <df:EntityProperty.editor>
                                                <df:PropertyEditor type="Decimal"/>
                                            </df:EntityProperty.editor>
                                        </df:EntityProperty>
                                        <df:EntityProperty name="stammumfang" displayName="Stammumfang in cm" columnIndex="0" index="5">
                                            <df:EntityProperty.editor>
                                                <df:PropertyEditor type="Number"/>
                                            </df:EntityProperty.editor>
                                        </df:EntityProperty>
                                        <df:EntityProperty name="hdVerhaeltnis" displayName="H/D Verhältnis" columnIndex="1" index="5" readOnly="true">
                                            <df:EntityProperty.editor>
                                                <df:PropertyEditor type="Decimal"/>
                                            </df:EntityProperty.editor>
                                        </df:EntityProperty>
                                    </df:PropertyGroup.properties>

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
_(You can paste entire code snippets, link to playground demo or attach a runnable project)_

**Comment by wyong95** [comment]
Any update on this ???

**Comment by wkjesus** [comment]
I have se same situation, !! any progress.?
