### ISSUE TITLE
RadSideDrawer Fatal Exception: java.lang.RuntimeException Caused by com.tns.NativeScriptException

### ISSUE THREAD

**Issue by ofarrellkevin0** [telerik/nativescript-ui-feedback#1540]
**Nativescript version: 7.2.1
Angular CLI: 10.2.3
Platform: Android (specifically Android 11 for the most part looks like the issue)**

Been developing an app with the specific versions up above and the specific platform for android mentioned seems to have an issue. The app builds and runs perfectly fine for the most part but every now and again once you open it the app try's to open but breaks and force closes. 

This issue has no real pattern for reproducing and only sporadically happens but it is causing issues for people.
I'm posting here to see can I get any feedback on this problem and is there potentially a fix for this?
I've also attached my dependencies and dev dependencies from the package.json below this along with the firebase logs for the error. In case it is of any use I also will include the command I use to run the app. 

`ns debug android --bundle --no-hmr
`
```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.app.app/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed Error: java.lang.NoSuchMethodError: no non-static method "Lcom/telerik/android/primitives/widget/sidedrawer/RadSideDrawer;.setMainContent(Ljava/lang/String;)Ljava/io/File;"
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3792)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)

Caused by com.tns.NativeScriptException
Calling js method onCreate failed Error: java.lang.NoSuchMethodError: no non-static method "Lcom/telerik/android/primitives/widget/sidedrawer/RadSideDrawer;.setMainContent(Ljava/lang/String;)Ljava/io/File;"
com.tns.Runtime.callJSMethodNative (Runtime.java)
com.tns.Runtime.dispatchCallJSMethodNative (Runtime.java:1302)
com.tns.Runtime.callJSMethodImpl (Runtime.java:1188)
com.tns.Runtime.callJSMethod (Runtime.java:1175)
com.tns.Runtime.callJSMethod (Runtime.java:1153)
com.tns.Runtime.callJSMethod (Runtime.java:1149)
com.tns.NativeScriptActivity.onCreate (NativeScriptActivity.java:29)
android.app.Activity.performCreate (Activity.java:8198)
android.app.Activity.performCreate (Activity.java:8182)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1309)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3765)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3968)
android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2307)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8512)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

```
     "dependencies": {
        "@angular/animations": "^10.2.3",
        "@angular/cdk": "^10.2.3",
        "@angular/language-service": "^10.2.3",
        "@angular/material": "^10.2.3",
        "@angular/platform-browser": "^10.2.3",
        "@angular/platform-browser-dynamic": "^10.2.3",
        "@angular/router": "^10.2.3",
        "@auth0/angular-jwt": "5.0.2",
        "@datorama/akita": "^6.1.3",
        "@nativescript/angular": "10.1.7",
        "@nativescript/core": "7.2.2",
        "@nativescript/firebase": "11.1.3",
        "@nativescript/theme": "~3.0.1",
        "@nativescript/webpack": "~4.1.0",
        "@ng-select/ng-select": "^5.1.0",
        "@nstudio/nativescript-filterable-listpicker": "3.0.0",
        "@types/chart.js": "^2.7.36",
        "angular-bootstrap-md": "^10.1.1",
        "angular-webstorage-service": "^1.0.2",
        "bootstrap": "^4.1.3",
        "chart.js": "^2.5.0",
        "classlist.js": "^1.1.20150312",
        "core-js": "^2.5.4",
        "font-awesome": "^4.7.0",
        "hammerjs": "^2.0.8",
        "jquery": "^3.3.1",
        "lodash": "^4.17.15",
        "nativescript-barcodescanner": "^3.2.2",
        "nativescript-insomnia": "^1.2.3",
        "nativescript-iqkeyboardmanager": "^1.3.0",
        "nativescript-phone": "^1.4.0",
        "nativescript-sqlite": "2.6.2",
        "nativescript-theme-core": "~1.0.4",
        "nativescript-ui-autocomplete": "7.0.2",
        "nativescript-ui-calendar": "7.0.2",
        "nativescript-ui-chart": "8.0.2",
        "nativescript-ui-listview": "9.1.0",
        "nativescript-ui-sidedrawer": "9.0.3",
        "nativescript-webview-interface": "^1.4.3",
        "nativescript-zip": "^3.0.3",
        "ngx-cookie-service": "^1.0.10",
        "ngx-toastr": "^13.2.1",
        "popper.js": "^1.14.5",
        "reflect-metadata": "~0.1.8",
        "roboto-fontface": "^0.10.0",
        "rxjs": "~6.6.7",
        "rxjs-compat": "^6.5.3",
        "web-animations-js": "^2.3.1",
        "websocket-driver": "^0.7.3",
        "zone.js": "~0.10.2"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.1002.3",
        "@angular/common": "^10.2.3",
        "@angular/compiler": "^10.2.3",
        "@angular/compiler-cli": "^10.2.3",
        "@angular/core": "^10.2.3",
        "@angular/forms": "^10.2.3",
        "@angular/localize": "^10.2.3",
        "@nativescript/android": "8.0.0",
        "@nativescript/ios": "7.2.0",
        "@nativescript/schematics": "~11.2.0",
        "@nativescript/tslint-rules": "~0.0.5",
        "@nativescript/types": "~7.0.0",
        "@ngtools/webpack": "~10.2.3",
        "@types/jasmine": "~3.3.8",
        "@types/jasminewd2": "~2.0.3",
        "@types/lodash": "^4.14.150",
        "@types/node": "14.6.0",
        "codelyzer": "^6.0.2",
        "fibers": "^5.0.0",
        "html-webpack-plugin": "^4.5.2",
        "jasmine-core": "~3.8.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "^1.4.0",
        "nativescript-dev-appium": "^5.1.0",
        "ng-packagr": "^10.0.0",
        "node-sass": "^4.7.1",
        "postcss": "^8.1.0",
        "protractor": "~5.4.0",
        "ts-node": "~7.0.0",
        "ts-patch": "1.3.3",
        "tslib": "2.0.0",
        "tslib-legacy": "npm:tslib@^1.8.0",
        "tslint": "^5.16.0",
        "typescript": "3.9.7"
    },
```

**Comment by glenranson** [comment]
Was there any fix for this issue, Looks like we are having the same issue with our app.
`StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.vixapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
Error: java.lang.NoSuchMethodError: no non-static method "Lcom/telerik/android/primitives/widget/sidedrawer/RadSideDrawer;.setMainContent(Ljava/lang/String;)[B"
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
Error: java.lang.NoSuchMethodError: no non-static method "Lcom/telerik/android/primitives/widget/sidedrawer/RadSideDrawer;.setMainContent(Ljava/lang/String;)[B"
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	... 11 more
Caused by: java.lang.NoSuchMethodError: no non-static method "Lcom/telerik/android/primitives/widget/sidedrawer/RadSideDrawer;.setMainContent(Ljava/lang/String;)[B"
	... 22 more`
