### ISSUE TITLE
RadListView crashes with NS 8.2 when pullToRefresh = true

### ISSUE THREAD

**Issue by jyl087** [telerik/nativescript-ui-feedback#1544]
### Which platform(s) does your issue occur on?
So far, have only tested on Android. 

### Please provide the following version numbers that your issue occurs with:
- "nativescript-ui-listview": "^10.0.2",
- **CLI:** : 8.2.2
- "@nativescript/android": "^8.2.2",
- 
### Please tell us how to recreate the issue in as much detail as possible.

Simply setting pullToRefresh to "true" causes the component to crash and not load. Blank screen is displayed. Removing the property or setting it to "false" allows the component to load.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

<RadListView [items]="items" ..... pullToRefresh="true"

**Comment by alexander-mai** [comment]
I have the same error on Android.

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.lang.VerifyError: Verifier rejected class com.telerik.widget.list.SwipeRefreshBehavior: androidx.swiperefreshlayout.widget.SwipeRefreshLayout com.telerik.widget.list.SwipeRefreshBehavior.swipeRefresh() failed to verify: androidx.swiperefreshlayout.widget.SwipeRefreshLayout com.telerik.widget.list.SwipeRefreshBehavior.swipeRefresh(): [0x2]  can't resolve returned type 'Unresolved Reference: androidx.swiperefreshlayout.widget.SwipeRefreshLayout' or 'Unresolved Reference: com.telerik.widget.list.SwipeRefreshBehavior$SwipeRefreshIndicator' (declaration of 'com.telerik.widget.list.SwipeRefreshBehavior' appears in /data/app/~~dDnqDRVy5fqO2gB_lngv9Q==/my.app-_fgNTTImAANOC9ICgr6nwg==/base.apk)
System.err: 
System.err: StackTrace:
System.err: updatePullToRefreshBehavior(file:///data/data/my.app/files/app/vendor.js:87325:47)
System.err:     at createNativeView(file:///data/data/my.app/files/app/vendor.js:86651:14)
System.err:     at _setupUI(file:///data/data/my.app/files/app/vendor.js:27310:31)
System.err:     at (file:///data/data/my.app/files/app/vendor.js:27354:19)
System.err:     at eachChildView(file:///data/data/my.app/files/app/vendor.js:38382:28)
System.err:     at eachChild(file:///data/data/my.app/files/app/vendor.js:29777:14)
System.err:     at _setupUI(file:///data/data/my.app/files/app/vendor.js:27353:14)
System.err:     at (file:///data/data/my.app/files/app/vendor.js:27354:19)
System.err:     at eachChildView(file:///data/data/my.app/files/app/vendor.js:38382:28)
System.err:     at eachChild(file:///data/data/my.app/files/app/vendor.js:29777:14)
System.err:     at _setupUI(file:///data/data/my.app/files/app/vendor.js:27353:14)
System.err:     at (file:///data/data/my.app/files/app/vendor.js:27354:19)
System.err:     at eachChildView(file:///data/data/my.app/files/app/vendor.js:24503:13)
System.err:     at eachChildView(file:///data/data/my.app/files/app/vendor.js:40355:15)
System.err:     at eachChild(file:///data/data/my.app/files/app/vendor.js:29777:14)
System.err:     at _setupUI(file:///data/data/my.app/files/app/vendor.js:27353:14)
System.err:     at _addViewCore(file:///data/data/my.app/files/app/vendor.js:27203:18)
System.err:     at _addView(file:///data/data/my.app/files/app/vendor.js:27192:14)
System.err:     at onCreateView(file:///data/data/my.app/files/app/vendor.js:34191:13)
System.err:     at onCreateView(file:///data/data/my.app/files/app/vendor.js:31800:40)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
System.err:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
System.err:     at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
System.err:     at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loopOnce(Looper.java:226)
System.err:     at android.os.Looper.loop(Looper.java:313)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:8641)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
System.err: Caused by: java.lang.VerifyError: Verifier rejected class com.telerik.widget.list.SwipeRefreshBehavior: androidx.swiperefreshlayout.widget.SwipeRefreshLayout com.telerik.widget.list.SwipeRefreshBehavior.swipeRefresh() failed to verify: androidx.swiperefreshlayout.widget.SwipeRefreshLayout com.telerik.widget.list.SwipeRefreshBehavior.swipeRefresh(): [0x2]  can't resolve returned type 'Unresolved Reference: androidx.swiperefreshlayout.widget.SwipeRefreshLayout' or 'Unresolved Reference: com.telerik.widget.list.SwipeRefreshBehavior$SwipeRefreshIndicator' (declaration of 'com.telerik.widget.list.SwipeRefreshBehavior' appears in /data/app/~~dDnqDRVy5fqO2gB_lngv9Q==/my.app-_fgNTTImAANOC9ICgr6nwg==/base.apk)
System.err:     ... 22 more
```

**Comment by jeremyr-corteva** [comment]
we are having the exact same issue, but with v9.1.4 of the listview plugin.  Tried upgrading to 10+ but it appears to have a dependency on angular 14 (we are running 12).
