### ISSUE TITLE
[RadSideDrawer] Navigate with a clearHistory broke RadSideDrawer.

### ISSUE THREAD

**Issue by agylmaxlach** [telerik/nativescript-ui-feedback#169]
When I make a navigate clearHistory to the page with a RadSideDrawer I get this error :
Does anyone know how to fix it ?
`this.routerExtensions.navigate(['/forms'], { animated: false, clearHistory: true });`

> JS: ERROR Error: Uncaught (in promise): ObjectUnsubscribedError: object unsubscribed
> JS: Error: object unsubscribed
> JS:     at ObjectUnsubscribedError.ZoneAwareError (file:///data/data/com.devalto.formalto/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:993:33)
> JS:     at new ObjectUnsubscribedError (file:///data/data/com.devalto.formalto/files/app/tns_modules/rxjs/util/ObjectUnsubscribedError.js:19:26)
> JS:     at EventEmitter.Subject._trySubscribe (file:///data/data/com.devalto.formalto/files/app/tns_modules/rxjs/Subject.js:94:19)
> JS:     at EventEmitter.Observable.subscribe (file:///data/data/com.devalto.formalto/files/app/tns_modules/rxjs/Observable.js:45:27)
> JS:     at EventEmitter.subscribe (file:///data/data/com.devalto.formalto/files/app/tns_modules/@angular/core/bundles/core.umd.js:3857:43)
> JS:     at TranslatePipe.transform (file:///data/data/com.devalto.formalto/files/app/tns_modules/@ngx-translate/core/bundles/core.umd.js:1152:61)
> JS:     at Object.eval [as updateRenderer] (ng:///AppModule/LoginComponent.ngfactory.js:808:68)
> JS:     at Object.updateRenderer (file:///data/data/com.devalto.formalto/files/app/tns_modules/@angular/core/bundles/core.umd.js:12435:70)
> JS:     at checkAndUpdateView (file:///data/data/com.devalto.formalto/files/app/tns_modules/@angular/core/bundles/core.umd.js:12037:14)
> JS:     at callViewAction (file:///data/data/com.devalto.formalto/files/app/tns_modules/@angular/core/bundles/core.umd.js:12347:17)
> JS:     at execComponentViewsAction (file:///data/data/com.devalto.formalto/files/app/tns_modules/@angular/core/bundles/core.umd.js:12293:13)
> JS:     at Object.checkAndUpdateView (file:///data/data/com.devalto.formalto/files/app/tns_modules/@angular/core/bundles/core.umd.js:12038:5)
> JS:     at ViewRef_.detectChanges (file:///data/data/com.devalto.formalto/files/app/tns_modules/@angular/core/bundles/core.umd.js:10129:63)
> JS:     at PageRouterOutlet.activateOnGoForward (file:///data/data/com.devalto.formalto/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:168:57)
> JS:     at PageRouterOutlet.activateWith (file:///data/data/com.devalto.formalto/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:138:18)

**Comment by VladimirAmiorkov** [comment]
Hi @agylmaxlach ,

Can you share with us a runnable project or the code snippets of the component to which you are navigating to and how the RadSideDrawer is setup. From the provided stack trace I do not see any RadSideDrawer references, does removing the RadSideDrawer resolve this issue ?

**Comment by agylmaxlach** [comment]
RadSideDrawer :
[menu.txt](https://github.com/telerik/nativescript-ui-feedback/files/979500/menu.txt)

The action I do to change the page (this one is inside the 'da-drawer-menu'):
this.routerExtensions.navigate(['/forms'], { clearHistory: true });

And there is the routing :
[routing.txt](https://github.com/telerik/nativescript-ui-feedback/files/979514/routing.txt)

**Comment by VladimirAmiorkov** [comment]
Hi @agylmaxlach ,

I apologize for getting back to you this late. thank you for the additional information.

I did try the described navigation to a Component that includes the RadSideDrawer while clearing the history by passing the { clearHistory: true } to the router extensions and was not able to observe the described issue. Could you updated to our latest version of the "nativescript-telerik-ui": "3.0.1" and to "nativescript-angular": "3.1.1" and see if you still observe such issues in your project.

**Comment by DimitarTodorov** [comment]
Closing due to inactivity.
