### ISSUE TITLE
Exception in thread "main" when create release apk

### ISSUE THREAD

**Issue by naturalfreak** [telerik/nativescript-ui-feedback#319]
When I updated nativescript-telerik-ui-pro to nativescript-pro-ui and tried to create release apk

npm run build-android-bundle -- --release --keyStorePath store.path --keyStorePassword store.password --keyStoreAlias alias.name --keyStoreAliasPassword alias.password

or better way

npm run build-android-bundle -- --release --uglify --snapshot --keyStorePath store.path --keyStorePassword store.password --keyStoreAlias alias.name --keyStoreAliasPassword alias.password

I tested with this [repo](https://github.com/telerik/nativescript-ui-samples-angular).
I got the same error in my project.

```
Exception in thread "main" java.lang.ClassNotFoundException: Class: android.support.v7.widget.RecyclerView$Adapter
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:709)
        at org.nativescript.staticbindinggenerator.Generator.collectInterfaceMethods(Generator.java:675)
        at org.nativescript.staticbindinggenerator.Generator.getPublicApi(Generator.java:212)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:326)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:117)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:157)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:77)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:54)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)

FAILURE: Build failed with an exception.
```

**Comment by tgpetrov** [comment]
As also noted [here](https://github.com/NativeScript/android-runtime/issues/858), the issue will be resolved with the next official release which is expected later this month.
