### ISSUE TITLE
App crashes when opening after system kill because of low memory

### ISSUE THREAD

**Issue by victorevox** [telerik/nativescript-ui-feedback#467]
### Tell us about the problem
After system kills the app because of low memory or other reason when opening again the app, the first startup crash, the error seems to be something related to the Sidedrawer.
My project is made with **nativescript +  Angular** 
I've checked if other apps have this error and it seems that another open source project made with Angular has this similar crash: https://github.com/EddyVerbruggen/nativescript-pluginshowcase

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** ^3.2.0
- **CLI:** 3.3.1
- **Cross-platform modules:** ^3.3.0
- **Runtime(s):** `"tns-android"` 3.3.1

### Please tell us how to recreate the issue in as much detail as possible.
In order to replicate low memory kill:
1. Got to Android Developer options
2. Activate "Don't keep activities" option to kill app when leaving
3. Start Application 
4. Go to home or another app
5. Return to the main app, it will crash, you need to close and open it again

Here is the logcat:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.insidethegoodlife.app/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: java.lang.Error: java.lang.ClassNotFoundException: Invalid name: ������������������8������o
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState.<init>(SideDrawerState.java:63)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:11)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:8)
    android.os.Parcel.readParcelable(Parcel.java:2471)
    android.os.Parcel.readValue(Parcel.java:2365)
    android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
    android.os.Parcel.readSparseArray(Parcel.java:2068)
    android.os.Parcel.readValue(Parcel.java:2422)
    android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
    android.os.BaseBundle.unparcel(BaseBundle.java:270)
    android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:915)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
    android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2034)
    android.app.FragmentController.dispatchCreate(FragmentController.java:165)
    android.app.Activity.onCreate(Activity.java:961)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6684)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
    android.app.ActivityThread.-wrap12(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6236)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.ClassNotFoundException: Invalid name: ������������������8������o
    java.lang.Class.classForName(Native Method)
    java.lang.Class.forName(Class.java:400)
    java.lang.Class.forName(Class.java:326)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState.<init>(SideDrawerState.java:58)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:11)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:8)
    android.os.Parcel.readParcelable(Parcel.java:2471)
    android.os.Parcel.readValue(Parcel.java:2365)
    android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
    android.os.Parcel.readSparseArray(Parcel.java:2068)
    android.os.Parcel.readValue(Parcel.java:2422)
    android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
    android.os.BaseBundle.unparcel(BaseBundle.java:270)
    android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:915)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
    android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2034)
    android.app.FragmentController.dispatchCreate(FragmentController.java:165)
    android.app.Activity.onCreate(Activity.java:961)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6684)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
    android.app.ActivityThread.-wrap12(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6236)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
File: "file:///data/data/com.insidethegoodlife.app/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 610, column: 18

StackTrace: 
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.insidethegoodlife.app/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 610, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/com.insidethegoodlife.app/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: java.lang.Error: java.lang.ClassNotFoundException: Invalid name: ������������������8������o
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState.<init>(SideDrawerState.java:63)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:11)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:8)
    android.os.Parcel.readParcelable(Parcel.java:2471)
    android.os.Parcel.readValue(Parcel.java:2365)
    android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
    android.os.Parcel.readSparseArray(Parcel.java:2068)
    android.os.Parcel.readValue(Parcel.java:2422)
    android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
    android.os.BaseBundle.unparcel(BaseBundle.java:270)
    android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:915)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
    android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2034)
    android.app.FragmentController.dispatchCreate(FragmentController.java:165)
    android.app.Activity.onCreate(Activity.java:961)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6684)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
    android.app.ActivityThread.-wrap12(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6236)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: java.lang.ClassNotFoundException: Invalid name: ������������������8������o
    java.lang.Class.classForName(Native Method)
    java.lang.Class.forName(Class.java:400)
    java.lang.Class.forName(Class.java:326)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState.<init>(SideDrawerState.java:58)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:11)
    com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:8)
    android.os.Parcel.readParcelable(Parcel.java:2471)
    android.os.Parcel.readValue(Parcel.java:2365)
    android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
    android.os.Parcel.readSparseArray(Parcel.java:2068)
    android.os.Parcel.readValue(Parcel.java:2422)
    android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
    android.os.BaseBundle.unparcel(BaseBundle.java:270)
    android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:915)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
    android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2034)
    android.app.FragmentController.dispatchCreate(FragmentController.java:165)
    android.app.Activity.onCreate(Activity.java:961)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6684)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
    android.app.ActivityThread.-wrap12(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6236)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
File: "file:///data/data/com.insidethegoodlife.app/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 610, column: 18

StackTrace: 
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.insidethegoodlife.app/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 610, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/com.insidethegoodlife.app/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
	... 9 more
Caused by: java.lang.Error: java.lang.ClassNotFoundException: Invalid name: ���8�o
	at com.telerik.android.primitives.widget.sidedrawer.SideDrawerState.<init>(SideDrawerState.java:63)
	at com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:11)
	at com.telerik.android.primitives.widget.sidedrawer.SideDrawerState$1.createFromParcel(SideDrawerState.java:8)
	at android.os.Parcel.readParcelable(Parcel.java:2471)
	at android.os.Parcel.readValue(Parcel.java:2365)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2813)
	at android.os.Parcel.readSparseArray(Parcel.java:2068)
	at android.os.Parcel.readValue(Parcel.java:2422)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
	at android.os.BaseBundle.unparcel(BaseBundle.java:270)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:934)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:915)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
	at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2034)
	at android.app.FragmentController.dispatchCreate(FragmentController.java:165)
	at android.app.Activity.onCreate(Activity.java:961)
	... 19 more
Caused by: java.lang.ClassNotFoundException: Invalid name: ���8�o
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:400)
	at java.lang.Class.forName(Class.java:326)
	at com.telerik.android.primitives.widget.sidedrawer.SideDrawerState.<init>(SideDrawerState.java:58)
	... 35 more

```

**Comment by tsonevn** [comment]
Hi @victorevox 
I tested the described scenario while using [nativescript-pluginshowcase](https://github.com/EddyVerbruggen/nativescript-pluginshowcase) while the "Don't keep activities" option was activated, and I was able to recreate the similar issue.
Regarding that, we will verify what it is causing this problem and if it is release related to the SideDrawer component.
In the meantime, I would suggest upgrading your project to the latest NativeScript 3.4 and to verify if you will have the same problem.
