### ISSUE TITLE
Fail to modify styles of a custom editor in DataForm

### ISSUE THREAD

**Issue by wanpeng2008** [telerik/nativescript-ui-feedback#582]
I have a custom editor working well without style setting. But it got error after i trying to modify the label position like this,

```
<TKEntityProperty tkDataFormProperty name="age" index="1">
    <TKCustomPropertyEditor tkEntityPropertyEditor (editorNeedsView)="editorNeedsView($event)" (editorHasToApplyValue)="editorHasToApplyValue($event)"
 (editorNeedsValue)="editorNeedsValue($event)">
        <TKPropertyEditorStyle tkPropertyEditorStyle labelPosition="Left"></TKPropertyEditorStyle> <== added here
	</TKCustomPropertyEditor>
</TKEntityProperty>

```
Here is the error message:
```
ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[TKPropertyEditorStyleDirective -> TKPropertyEditorDirective]: 
JS:   StaticInjectorError(Platform: core)[TKPropertyEditorStyleDirective -> TKPropertyEditorDirective]: 
JS:     NullInjectorError: No provider for TKPropertyEditorDirective!
JS: Error: NullInjectorError: No provider for TKPropertyEditorDirective!
JS:     at _NullInjector.get (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:1033:19) [angular]
JS:     at resolveToken (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:1331:24) [angular]
JS:     at tryResolveToken (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:1273:16) [angular]
JS:     at StaticInjector.get (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:1141:20) [angular]
JS:     at resolveToken (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:1331:24) [angular]
JS:     at tryResolveToken (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:1273:16) [angular]
JS:     at StaticInjector.get (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:1141:20) [angular]
JS:     at resolveNgModuleDep (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:10886:25) [angular]
JS:     at NgModuleRef_.get (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:12119:16) [angular]
JS:     at resolveNgModuleDep (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:10886:25) [angular]
JS:     at NgModuleRef_.get (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:12119:16) [angular]
JS:     at resolveDep (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:12609:45) [angular]
JS:     at createClass (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:12473:29) [angular]
JS:     at createDirectiveInstance (file:///data/data/org.nativescript.MarketingAssistant/files/app/tns_modules/@angular/core/bundles/core.umd.js:12316:37) [angular]
```

my env:
│ nativescript     │ 3.4.3  
│ tns-core-modules │ 3.4.1 
│ tns-android      │ 3.4.2     
    "nativescript-ui-autocomplete": "^3.6.0",
    "nativescript-ui-calendar": "^3.5.1",
    "nativescript-ui-chart": "^3.5.0",
    "nativescript-ui-dataform": "^3.5.0",
    "nativescript-ui-gauge": "^3.5.0",
    "nativescript-ui-listview": "^3.5.1",
    "nativescript-ui-sidedrawer": "^3.5.0",

**Comment by tsonevn** [comment]
Hi @wanpeng2008,
While using TKCustomPropertyEditor you should set up `TKCustomPropertyEditorStyle`. To solve the issue in the project, you should replace `TKPropertyEditorStyle` with `TKCustomPropertyEditorStyle`. For example:
```
<RadDataForm tkExampleTitle tkToggleNavButton [source]="person">
    <TKEntityProperty tkDataFormProperty name="name" index="0"></TKEntityProperty>
    <TKEntityProperty tkDataFormProperty name="age" index="1">
        <TKCustomPropertyEditor tkEntityPropertyEditor (editorNeedsView)="editorNeedsView($event)" (editorHasToApplyValue)="editorHasToApplyValue($event)"
         (editorNeedsValue)="editorNeedsValue($event)">
            <TKCustomPropertyEditorStyle tkCustomPropertyEditorStyle strokeColor="#00695c" strokeWidth="2" fillColor="#4db6ac" labelHidden="false"
            labelTextSize="18" ios:labelFontName="Times New Roman" android:labelFontName="sans-serif-light" labelFontStyle="Italic"
            labelPosition="Left" labelWidth="60" labelTextColor="#00695c"></TKCustomPropertyEditorStyle>
            </TKCustomPropertyEditor>
        </TKEntityProperty>
    <TKEntityProperty tkDataFormProperty name="birthDate" index="2">
        <TKPropertyEditor tkEntityPropertyEditor type="DatePicker"></TKPropertyEditor>
    </TKEntityProperty>
</RadDataForm>
```

**Comment by wanpeng2008** [comment]
Thanks @tsonevn, It works!
