### ISSUE TITLE
TokenModel is not a constructor

### ISSUE THREAD

**Issue by pankajjjpr** [telerik/nativescript-ui-feedback#676]
Using the link "http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/AutoCompleteTextView/getting-started", 
I tried to implement the AutoCompleteTextView into my app. the project built successfully and app also started. But when i clicked on that page where i implemented this code, I was getting below error:

**TypeError: com.telerik.widget.autocomplete.TokenModel is not a constructor**

Full error is as follows:
JS: ERROR Error: Uncaught (in promise): TypeError: com.telerik.widget.autocomplete.TokenModel is not a constructor
JS: TypeError: com.telerik.widget.autocomplete.TokenModel is not a constructor
JS:     at new TokenModel (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/nativescript-ui-autocomplete/ui-autocomplete.js:20:30)
JS:     at RegisterComponent.initDataItems (file:///data/data/com.itneer.hotelmobile/files/app/components/register/register.component.js:44:30)
JS:     at new RegisterComponent (file:///data/data/com.itneer.hotelmobile/files/app/components/register/register.component.js:32:14)
JS:     at createClass (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:10948:20)
JS:     at createDirectiveInstance (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:10783:37)
JS:     at createViewNodes (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:12224:53)
JS:     at createRootView (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:12114:5)
JS:     at callWithDebugContext (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:13499:42)
JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:12803:12)
JS:     at ComponentFactory_.create (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:9893:46)
JS:     at ComponentFactoryBoundToModule.create (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:3365:29)
JS:     at ViewContainerRef_.createComponent (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/@angular/core/bundles/core.umd.js:10091:62)
JS:     at DetachedLoader.loadWithFactory (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/nativescript-angular/common/detached-loader.js:38:34)
JS:     at PageRouterOutlet.activateOnGoForward (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:235:49)
JS:     at PageRouterOutlet.activateWith (file:///data/data/com.itneer.hotelmobile/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:211:14)

Version of "nativescript-ui-autocomplete": "^3.7.0"
Version of "tns-core-modules": "^3.4.1"
Version of tns : 4.0.0
Version of tns-android : 4.0.1

Below is the code, which I used:

**at HTML page:** 

<RadAutoCompleteTextView #autocmp [items]="dataItems" suggestMode="Suggest" displayMode="Tokens">
    <SuggestionView tkAutoCompleteSuggestionView>
        <ng-template tkSuggestionItemTemplate let-item="item">
            <StackLayout orientation="vertical" padding="10">
                <Label [text]="item.text"></Label>
            </StackLayout>
        </ng-template>
    </SuggestionView>
</RadAutoCompleteTextView>

**at .ts page:**
import { Component, OnInit, ViewChild } from "@angular/core";
import { ObservableArray } from "tns-core-modules/data/observable-array";
import { TokenModel } from "nativescript-ui-autocomplete";
import { RadAutoCompleteTextViewComponent } from "nativescript-ui-autocomplete/angular";

export class RegisterComponent {
    private _items: ObservableArray<TokenModel> ;

public constructor() {
        this.initDataItems();
    }

@ViewChild("autocmp") autocmp: RadAutoCompleteTextViewComponent;

    get dataItems(): ObservableArray<TokenModel> {
        return this._items;
    }

    private initDataItems() {
        this._items = new ObservableArray<TokenModel>();

        for (var i = 0; i < this.countries.length; i++) {
            this._items.push(new TokenModel(this.countries[i], undefined));
        }
    }
}

Please let me know if you have any idea around this or any other info you need.

**Comment by pankajjjpr** [comment]
Had to remove and add android platform and then did npm install. the issue got resolved.

**Comment by pankajjjpr** [comment]
Had to remove and add android platform and then did npm install. the issue got resolved.
