### ISSUE TITLE
Memory Consumption is high when use pullToRefresh

### ISSUE THREAD

**Issue by nmongiya** [telerik/nativescript-ui-feedback#717]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
https://discourse.nativescript.org/t/memory-management-for-app/6592

I have a requirement for my app to update the list in every few seconds using pullTorefresh. I am using REST call to get the data from server, process it (some filters and mapping) and assign to RadlistView. 

I have noticed that after 5-10 minutes app becomes very unresponsive and list actually freeze to scroll.
When I check the memory, it looks kike app used memory is increasing on every REST call.

`var mi = new android.app.ActivityManager.MemoryInfo();
var activityManager = application.android.context.getSystemService(android.content.Context.ACTIVITY_SERVICE);
activityManager.getMemoryInfo(mi);
let usedMemory = mi.totalMem - mi.availMem;
console.log("Percentage usage: " + (usedMemory / mi.totalMem)*100);
console.log("Used memory (megabytes): " + (usedMemory/1000000));`

P.S. I have even tried without making a REST call on pullToRefresh and check memory before and after and it is increasing.

**Comment by nmongiya** [comment]
I have created a new project using tns create myApp --ng and just made the change to load the data, instead of loading item locally I am making a rest call to load the data.

Another interesting point to note is memory consumption is increasing after each REST call (it returns ~135 kb data). Here is my log after few pull to refresh
used memory is 569.884672 and Percentage usage in : After pull to refresh   35.89
JS: used memory is 578.424832 and Percentage usage in : After pull to refresh   36.43
JS: used memory is 580.980736 and Percentage usage in : After pull to refresh   36.59
JS: used memory is 581.267456 and Percentage usage in : After pull to refresh   36.61
JS: used memory is 581.640192 and Percentage usage in : After pull to refresh   36.63
JS: used memory is 582.750208 and Percentage usage in : After pull to refresh   36.70
JS: used memory is 585.150464 and Percentage usage in : After pull to refresh   36.85
JS: used memory is 585.146368 and Percentage usage in : After pull to refresh   36.85
JS: used memory is 580.161536 and Percentage usage in : After pull to refresh   36.54
JS: used memory is 581.644288 and Percentage usage in : After pull to refresh   36.63
JS: used memory is 583.467008 and Percentage usage in : After pull to refresh   36.74
JS: used memory is 569.085952 and Percentage usage in : After pull to refresh   35.84
JS: used memory is 572.526592 and Percentage usage in : After pull to refresh   36.06

**Comment by NickIliev** [comment]
@nmongiya can you provide a sample porject or [Playground](https://play.nativescript.org/). Based on the log above it seems that the memory is released on some interval of time and at the end, the consumed memory is even a smaller amount than the initial one (started 578.42 - finished at 572.52) - or am I wrong?

**Comment by nmongiya** [comment]
This was the playground that I have created https://play.nativescript.org/?template=play-ng&id=7dolAE&v=8

**Comment by nmongiya** [comment]
Reference : https://github.com/telerik/nativescript-ui-feedback/issues/748

**Comment by nmongiya** [comment]
I tried with "tns-android": { "version": "4.2.0"  } "tns-core-modules": "^4.2.0", &  "nativescript-ui-listview": "^3.6.0", and notice that couple of time app is crashing with below error.

`An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: Attempt to use cleared object reference id=199792
at com.tns.Runtime.getJavaObjectByID(Runtime.java:923)
at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
at com.tns.Runtime.callJSMethod(Runtime.java:983)
at com.tns.Runtime.callJSMethod(Runtime.java:967)
at com.tns.Runtime.callJSMethod(Runtime.java:959)
at com.tns.gen.com.telerik.widget.list.ListViewDataSourceAdapter_listview_272_32_ListViewDataSourceAdapter.onCreateItemViewHolder(ListViewDataSourceAdapter_listview_272_32_ListViewDataSourceAdapter.java:42)
at com.telerik.widget.list.ListViewDataSourceAdapter.onCreateViewHolder(ListViewDataSourceAdapter.java:430)
at com.telerik.widget.list.ListViewWrapperAdapter.onCreateListViewHolder(ListViewWrapperAdapter.java:465)
at com.telerik.widget.list.ListViewAdapterBase.onCreateViewHolder(ListViewAdapterBase.java:145)
at com.telerik.widget.list.ListViewAdapterBase.onCreateViewHolder(ListViewAdapterBase.java:22)
at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
at com.telerik.widget.list.RadListView.onLayout(RadListView.java:589)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:945)
at android.view.View.layout(View.java:20854)
at android.view.ViewGroup.layout(ViewGroup.java:6401)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2912)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2599)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1743)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7773)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6949)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
`
