### ISSUE TITLE
SideDrawer fails to initialize on android device

### ISSUE THREAD

**Issue by noomieware** [telerik/nativescript-ui-feedback#755]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
After switching from pro-ui to nativescript-ui-sidedrawer incl. updating the imports. The application does not start on an android device with

System.err: TypeError: this._android.setAllowEdgeSwipe is not a function

### Which platform(s) does your issue occur on?
_Android 6.0.1_

### Please provide the following version numbers that your issue occurs with:

-  "nativescript-ui-sidedrawer": "^4.2.0",

$ tns --version
4.1.2

    "tns-android": {
      "version": "4.1.3"
    }

    "nativescript-angular": "^6.0.6",

FullStack

```
System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err: TypeError: this._android.setAllowEdgeSwipe is not a function
System.err: File: "file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js, line: 153, column: 22
System.err: StackTrace:
System.err:     Frame: function:'RadSideDrawer.createNativeView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js', line: 153, column: 23
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 492, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err:     Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 588, column: 24
System.err:     Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.charenjiapp/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err:     at android.app.Fragment.performCreateView(Fragment.java:2229)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:793)
System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5585)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
ActivityManager: Process org.nativescript.app (pid 14115) has died
ActivityManager: cleanUpApplicationRecord -- 14115
```

**Comment by tsonevn** [comment]
Hi @noomieware,
I tested your case with [our sample project](ipt-ui-samples-angular/tree/master/sidedrawer), however, was unable to recreate a similar issue. It will help if you send us sample project, which can be used for debugging.

**Comment by liuwei108** [comment]
Don't use live-sync, delete the app from android and reinstall will get rid of this err in my case. hope it helps!

**Comment by noomieware** [comment]
as stated by @felix-idf , the issue is gone with the new version of the package.
