### ISSUE TITLE
RadListView full-width header using StaggeredLayout

### ISSUE THREAD

**Issue by felix-idf** [telerik/nativescript-ui-feedback#771]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes_

### Tell us about the problem
Is there a possibility to stretch the headerItemTemplate to full-width of the screen on Android using StaggeredLayout like it already works on iOS?
We would like to use the StaggeredLayout in some of our ListViews, but we also need the header-functionality in certain situations, but the way it works right now on Android is not applicable for us.

![rlv_header_staggered](https://user-images.githubusercontent.com/6443021/43580941-6610fd40-9657-11e8-9a35-24f80a00edd0.png)

Is this just a bug or is it the expected behaviour on Android?

### Which platform(s) does your issue occur on?
_Android_

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** nativescript-ui-listview 3.5.11
- **CLI:** 4.1.2
- **Cross-platform modules:** 4.1.1
- **Runtime(s):** tns-android 4.1.3, tns-ios 4.1.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
[RLVLayoutHeaderIssue.zip](https://github.com/telerik/nativescript-ui-feedback/files/2253278/RLVLayoutHeaderIssue.zip)

**Comment by felix-idf** [comment]
It seems to be the default behaviour of the Android RecyclerView to draw the header view with the width of only one single span using the _android.support.v7.widget.StaggeredGridLayoutManager_.

But the RadListView is a cross-platform component and I think there should be a way that the RadListView StaggeredLayout header/footer is bahaving the same way on Android and iOS: taking the full width of the RadListView (like it alredy does on iOS by default) and not only one span.

On native Android development, it can be done like [this](https://stackoverflow.com/a/32210954).
[Here](https://github.com/willblaschko/header-footer-recycler-view/blob/24608ae12678b9d073b935826720d4cfb68833c7/app/src/main/java/com/willblaschko/android/headerfooterrecyclerview/RecyclerViewHeaderFooterAdapter.java#L127) is another example.

Right now, it might be a workaround to trigger the `loaded` event of the child of the headerViewTemplate like this:
```
...
<lv:RadListView.headerItemTemplate>
                <StackLayout loaded="onHeaderLoaded">
                    <Label text="I am the listview header..."/>
                </StackLayout>
</lv:RadListView.headerItemTemplate>
...
```

And run this code on Android:
```
exports.onHeaderLoaded = function(args) {
    if(args.object.android) {
        try {
            var layoutParams = new android.support.v7.widget.StaggeredGridLayoutManager.LayoutParams(android.view.ViewGroup.LayoutParams.MATCH_PARENT, android.view.ViewGroup.LayoutParams.WRAP_CONTENT);
            layoutParams.setFullSpan(true);
            args.object.android.setLayoutParams(layoutParams);
        } catch(e) {
            console.log(e);
        }
    }
};
```

But it would be nice if this could be included into the RadListView component by default. Otherewise the StaggeredLayout makes no sense.

**Comment by felix-idf** [comment]
There is a problem with the provided workaround:

When you are in the RadListView page, then tap an item to navigate to a detail page (for example) and then navigate back to the RadListView page, the following error occurs:

> System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView$ViewHolder.shouldIgnore()' on a null object reference
System.err: 	at android.support.v7.widget.RecyclerView.findMinMaxChildLayoutPositions(RecyclerView.java:3799)
System.err: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3536)
System.err: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3352)
System.err: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3886)
System.err: 	at com.telerik.widget.list.RadListView.onLayout(RadListView.java:589)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:611)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
System.err: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
System.err: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
System.err: 	at android.view.View.layout(View.java:17637)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:154)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by VladimirAmiorkov** [comment]
@felix-idf Hmm, looking at the stacktrace it looks like there might be an issue while the state of the list is being restored after you have changed one of its children layout params in this way. It looks like the onLayout of the RadListView is being called but the actual `holder` inside the `dispatchLayoutStep1` of that item's view is null. The holder is boing retraced by the RecyclerView like so, which looks ok to me:
`final ViewHolder holder = getChildViewHolderInt(mChildHelper.getChildAt(i));`

We will have to take a deeper look into this and see how we can implement such functionality because it looks to not be a trivial task.

**Comment by racknoris** [comment]
@VladimirAmiorkov Is there a different way to do it manually? Or solve @felix-idf 's problem with the workaround?

**Comment by racknoris** [comment]
@felix-idf it seems that if i call that function only once, it doesn't throw that error- that is, initiate some flag in the constructor, and use it inside the `loaded` function to check if it has been called before:

```

// initiate this.calledBefore to false

// actual function:
exports.onHeaderLoaded = function(args) {

    if (this.calledBefore) {
        return;
    }
    this.calledBefore = true;

    if(args.object.android) {
        try {
            var layoutParams = new android.support.v7.widget.StaggeredGridLayoutManager.LayoutParams(android.view.ViewGroup.LayoutParams.MATCH_PARENT, android.view.ViewGroup.LayoutParams.WRAP_CONTENT);
            layoutParams.setFullSpan(true);
            args.object.android.setLayoutParams(layoutParams);
        } catch(e) {
            console.log(e);
        }
    }
};
```

**Comment by gogoout** [comment]
For those who want to set height of the header directly. You can actually set height or width directly.

```typescript
onHeaderLoaded(args) {
        if (this.isHeaderLoaded) {
            return;
        }
        this.isHeaderLoaded = true;
        if (isAndroid) {
            try {
                const layoutParams = new android.support.v7.widget.StaggeredGridLayoutManager.LayoutParams(android.view.ViewGroup.LayoutParams.MATCH_PARENT, this.headerHeight * screen.mainScreen.scale);
                layoutParams.setFullSpan(true);
                args.object.android.setLayoutParams(layoutParams);
            } catch (e) {
                console.log(e);
            }
        }
    }
```
