### ISSUE TITLE
this._android.setAllowEdgeSwipe is not a function

### ISSUE THREAD

**Issue by arbalu** [telerik/nativescript-ui-feedback#781]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum] 
Yes

### Tell us about the problem
Getting the error TypeError: this._android.setAllowEdgeSwipe is not a function: this._android.setAllowEdgeSwipe is not a function on Nativescript with angular app

### Which platform(s) does your issue occur on?
Android V6.0

### Please provide the following version numbers that your issue occurs with:
Progress NativeScript UI version:
CLI: 4.2.0 
Cross-platform modules : 4.1.1 
Runtime(s): tns-android
Angular : 6.0.6 

### Please tell us how to recreate the issue in as much detail as possible.
1. Create Application 
2. Add sideDrawer to page
3.Build in window with android : 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
<RadSideDrawer [drawerTransition]="_sideDrawerTransition">
	<GridLayout tkDrawerContent rows="auto, *" class="sidedrawer sidedrawer-left">
		<StackLayout row="0" class="sidedrawer-header">
			<Label class="sidedrawer-header-image fa" text="&#xf2bd;"></Label>
			<Label class="sidedrawer-header-brand" text="User Name"></Label>
			<Label class="footnote" text="username@mail.com"></Label>
		</StackLayout>
		<ScrollView row="1">
			<StackLayout class="sidedrawer-content">
				<GridLayout columns="auto, *" class="sidedrawer-list-item">
					<Label col="0" text="&#xf015;" class="fa"></Label>
					<Label col="1" text="Home" class="p-r-10"></Label>
				</GridLayout>

				<GridLayout columns="auto, *" class="sidedrawer-list-item">
					<Label col="0" text="&#xf1ea;" class="fa"></Label>
					<Label col="1" text="Browse" class="p-r-10"></Label>
				</GridLayout>

				<GridLayout columns="auto, *" class="sidedrawer-list-item">
					<Label col="0" text="&#xf002;" class="fa"></Label>
					<Label col="1" text="Search" class="p-r-10"></Label>
				</GridLayout>

				<GridLayout columns="auto, *" class="sidedrawer-list-item">
					<Label col="0" text="&#xf005;" class="fa"></Label>
					<Label col="1" text="Featured" class="p-r-10"></Label>
				</GridLayout>

				<StackLayout class="hr-light"></StackLayout>

				<GridLayout columns="auto, *" class="sidedrawer-list-item">
					<Label col="0" text="&#xf013;" class="fa"></Label>
					<Label col="1" text="Settings" class="p-r-10"></Label>
				</GridLayout>
			</StackLayout>
		</ScrollView>
	</GridLayout>

	<page-router-outlet tkMainContent class="page page-content"></page-router-outlet>
</RadSideDrawer>
```

TS File 
```
import { Component, OnInit ,  ViewChild, AfterViewInit, ChangeDetectorRef } from "@angular/core";
import * as app from "application"; 
import { RouterExtensions } from "nativescript-angular/router";
import { DrawerTransitionBase, RadSideDrawer, SlideInOnTopTransition } from "nativescript-ui-sidedrawer";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-ui-sidedrawer/angular";

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html",
    styleUrls:['./home.component.css']
})
export class HomeComponent implements OnInit {
    public _sideDrawerTransition: DrawerTransitionBase; 
    private drawer: RadSideDrawer;
    constructor( ) {
        // Use the component constructor to inject providers.
    }
 

    ngOnInit(): void { 
        // Init your component properties here.
        this._sideDrawerTransition = new SlideInOnTopTransition();
    }

    get sideDrawerTransition(): DrawerTransitionBase {
        return this._sideDrawerTransition;
    }

    onDrawerButtonTap(): void {
       this._sideDrawerTransition.getNativeContent(); 
    }
    
}
```

Error
```
System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err: TypeError: this._android.setAllowEdgeSwipe is not a function
System.err: File: "file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js, line: 153, column: 22
System.err: StackTrace:
System.err:     Frame: function:'RadSideDrawer.createNativeView', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/nativescript-ui-sidedrawer/ui-sidedrawer.js', line: 153, column: 23
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 492, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err:     Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 588, column: 24
System.err:     Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.VEmailMarketApp/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
System.err:     at android.app.Fragment.performCreateView(Fragment.java:2220)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:793)
System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1537)
System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
System.err:     at android.os.Handler.handleCallback(Handler.java:746)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5443)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

Please let me know if you need more info on this.

**Comment by tsonevn** [comment]
Hi @arbalu,
I tested your case with latest tns-core-modules 4.2, nativescript-angular `6.1.0` and nativescript-ui-sidedrawer `4.2.1`, however, was unable to recreate the described problem.  For your convenience, I am attaching a sample project. Please review it and make the needed changes, which will allow us to recreate the issue.

[Archive.zip](https://github.com/telerik/nativescript-ui-feedback/files/2277450/Archive.zip)
