### ISSUE TITLE
Attempt to invoke method on a null object reference

### ISSUE THREAD

**Issue by tsonevn** [telerik/nativescript-ui-feedback#911]
_From @NickIliev on October 31, 2018 9:4_

Errors coming from Crashlytics (relatively rarely seen). All the errors are related to calling a method on a native object.

The errors below are happening on an application that is using the experimental feature `markingMode` set to `none` and might be related to GC.

The below errors does not have stable ways and detailed steps to reproduce so any additional information that can help to reproduce a similar crash can be logged here.

Reported via t.1348839  t.1348832, t.1348831, and t.1348830 

Error logs as follows (two of them directly related to `RadListView`): 

**Error 1** (RadListView related)
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference

       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5943)
       at com.telerik.widget.list.SwipeLayout.onMeasure(SwipeLayout.java:130)
       at android.view.View.measure(View.java:18836)
       at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9119)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1583)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
       at com.telerik.widget.list.RadListView.onLayout(RadListView.java:591)
       at android.view.View.layout(View.java:16678)
       at android.view.ViewGroup.layout(ViewGroup.java:5438)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
       at android.view.View.layout(View.java:16678)
```
**Error 2** (RadListView related)
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.RecyclerView$Adapter.getItemCount()' on a null object reference
       at com.telerik.widget.list.ListViewWrapperAdapter.getSpanSize(ListViewWrapperAdapter.java:89)
       at com.telerik.widget.list.RadListView$3.getSpanSize(RadListView.java:473)
       at android.support.v7.widget.GridLayoutManager$SpanSizeLookup.getSpanGroupIndex(GridLayoutManager.java:972)
       at android.support.v7.widget.GridLayoutManager.getSpanGroupIndex(GridLayoutManager.java:452)
       at android.support.v7.widget.GridLayoutManager.getRowCountForAccessibility(GridLayoutManager.java:126)
       at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10127)
       at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10087)
       at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:63)
       at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:70)
       at android.view.View.onInitializeAccessibilityNodeInfo(View.java:7343)
       at android.view.View.createAccessibilityNodeInfoInternal(View.java:7304)
       at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:26062)
       at android.view.View.createAccessibilityNodeInfo(View.java:7287)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1147)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1170)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1170)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:972)
       at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:336)
       at android.view.AccessibilityInteractionController.-wrap1(Unknown Source)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1324)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

_Copied from original issue: NativeScript/NativeScript#6479_

**Comment by zbranzov** [comment]
A possible fix is released in nativescript-ui-listview@3.8.0 but we cannot verify it as the error cannot be reproduced.
