### ISSUE TITLE
Sidedrawer apps crash when deployed on android 23

### ISSUE THREAD

**Issue by zbranzov** [telerik/nativescript-ui-feedback#918]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes
### Tell us about the problem
Sidedrawer apps crash when deployed on android 23. If you remove the sidedrawer it works.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 5.0.0
- **CLI:** 5.0.0
- **Cross-platform modules:** 5.0.0
- **Runtime(s):** 5.0.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application on android 23
2. It crashes 
System.err: android.content.res.Resources$NotFoundException: Resource ID #0xfffffff6
System.err:     at android.content.res.Resources.getValue(Resources.java:1351)
System.err:     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2774)
System.err:     at android.content.res.Resources.getAnimation(Resources.java:1189)
System.err:     at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:75)
System.err:     at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1102)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1600)
System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641)
System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
ActivityManager: Process org.nativescript.demoangular (pid 12995) has died

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
sidedrawer demo apps

**Comment by zbranzov** [comment]
It was error caused by CLI 4.2. Using 5.0 fixes it.
