### ISSUE TITLE
RadCalendar crash with NS 5.0 and Android SDK 28

### ISSUE THREAD

**Issue by adouglas0363** [telerik/nativescript-ui-feedback#930]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem
Exception is thrown when using inline event view mode with NativeScript V5.0 and Android SDK 28

An uncaught Exception occurred on "main" thread.
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
	at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
	at android.graphics.Canvas.clipRect(Canvas.java:826)
	at com.telerik.widget.calendar.CalendarFragment.drawRows(CalendarFragment.java:585)
	at com.telerik.widget.calendar.CalendarFragment.render(CalendarFragment.java:255)
	at com.telerik.widget.calendar.CalendarScrollManager$FragmentHolder$LayerView.onDraw(CalendarScrollManager.java:137)
	at android.view.View.draw(View.java:20207)
	at android.view.View.updateDisplayListIfDirty(View.java:19082)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.View.draw(View.java:19935)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
	at android.view.View.draw(View.java:20210)
	at android.view.View.updateDisplayListIfDirty(View.java:19082)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:19042)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Which platform(s) does your issue occur on?
Android (SDK 28)

### Please provide the following version numbers that your issue occurs with:
- **NativeScript UI Calendar:** 3.9
- **CLI:** 5.0
- **Cross-platform modules:** 5.0
- **Runtime(s):** 5.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Select an event on the calendar
3. Application will crash

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
See attached demo application

[calendar-demo.zip](https://github.com/telerik/nativescript-ui-feedback/files/2576861/calendar-demo.zip)

**Comment by tsonevn** [comment]
Hi @adouglas0363,
I tested the provided sample project on my side, however, was unable to recreate the issue. For your convenience, I am attaching video, which demonstrates the behaviour of the app on the device, that I used to build the project. 
[test.zip](https://github.com/telerik/nativescript-ui-feedback/files/2588378/test.zip)


Something that you can try is to clear up the project following the below-attached steps and to rebuild it:
1. delete `platforms`, `node_modules`, `hooks` folders and `package-lock.json` file.
2. run `npm i`
3. rebuild the project via `tns run android`

**Comment by adouglas0363** [comment]
Hello @tsonevn,

I'm not sure what could be different on your end, but am still getting the exception, both on the demo application I provided and also my production application. This seems directly related to SDK 28 which as you know is now a requirement to upgrade to NativeScript 5.0. Until this is resolved, I cannot update the large application I maintain for my company.

The changes in SDK 28 which appear to be reason for this issue are explained here. [https://developer.android.com/reference/android/graphics/Canvas#clipRect(android.graphics.RectF,%20android.graphics.Region.Op)](url)

I can only assume (since it is not open source) that the RadCalendar is using a `Region.Op` parameter other than `INTERSECT` or `DIFFERENCE`, which as explained in the link above is no longer allowed in SDK 28.

Thanks

**Comment by VladimirAmiorkov** [comment]
Hi @adouglas0363 ,

We are working on resolving this issue. It is being tested as we speak and we expect an patch version to be released as soon as possible in the next days. Stay tuned for updates.

**Comment by adouglas0363** [comment]
It is now working great. Thanks!
