### ISSUE TITLE
Angular UI Listview sample project throws error on tns run Android/IOS

### ISSUE THREAD

**Issue by anuragd7** [telerik/nativescript-ui-feedback#934]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:**  nativescript-ui-listbview: *  
- **CLI:**  4.2.4
- **Cross-platform modules:** 4.2.0
- **Runtime(s):** 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
1. Clone the [nativescript-ui-samples-angular project](https://github.com/telerik/nativescript-ui-samples-angular) . 
2. Move into the listview directory
3. tns run android  and tns run ios both throw error logs.and the app becomes non responsive after the initial listview is loaded.

Android error log

```
app/examples/header-footer/change-size-at-runtime/listview-change-size-at-runtime.component.ts(31,49): error TS2339: Property 'updateHeaderFooter' does not exist on type 'RadListView'.
app/examples/header-footer/change-size-at-runtime/listview-change-size-at-runtime.component.ts(76,41): error TS2339: Property 'updateHeaderFooter' does not exist on type 'RadListView'.
app/examples/load-on-demand/dynamic-size-auto/listview-dynamic-size-auto.component.ts(4,45): error TS2305: Module '"/Users/NRMac/Projects/nativescript-ui-samples-angular/listview/node_modules/nativescript-ui-listview/index"' has no exported member 'LoadOnDemandListViewEventData'.
app/examples/load-on-demand/dynamic-size-auto/listview-dynamic-size-auto.component.ts(51,13): error TS2554: Expected 0 arguments, but got 1.
app/examples/load-on-demand/dynamic-size-manual/listview-dynamic-size-manual.component.ts(4,45): error TS2305: Module '"/Users/NRMac/Projects/nativescript-ui-samples-angular/listview/node_modules/nativescript-ui-listview/index"' has no exported member 'LoadOnDemandListViewEventData'.
app/examples/load-on-demand/dynamic-size-manual/listview-dynamic-size-manual.component.ts(52,13): error TS2554: Expected 0 arguments, but got 1.
app/examples/load-on-demand/fixed-size-auto-with-small-source/listview-fixed-size-auto-with-small-source.component.ts(4,64): error TS2305: Module '"/Users/NRMac/Projects/nativescript-ui-samples-angular/listview/node_modules/nativescript-ui-listview/index"' has no exported member 'LoadOnDemandListViewEventData'.
app/examples/load-on-demand/fixed-size-auto-with-small-source/listview-fixed-size-auto-with-small-source.component.ts(69,17): error TS2554: Expected 0 arguments, but got 1.
app/examples/load-on-demand/fixed-size-auto-with-small-source/listview-fixed-size-auto-with-small-source.component.ts(92,17): error TS2554: Expected 0 arguments, but got 1.
app/examples/load-on-demand/fixed-size-auto-with-small-source/listview-fixed-size-auto-with-small-source.component.ts(96,13): error TS2554: Expected 0 arguments, but got 1.
app/examples/load-on-demand/fixed-size-auto-with-small-source/listview-fixed-size-auto-with-small-source.component.ts(137,9): error TS2322: Type 'ListViewLoadOnDemandMode' is not assignable to type 'string'.
app/examples/load-on-demand/fixed-size-auto-with-small-source/listview-fixed-size-auto-with-small-source.component.ts(141,9): error TS2322: Type 'ListViewLoadOnDemandMode' is not assignable to type 'string'.
app/examples/load-on-demand/fixed-size-auto-with-small-source/listview-fixed-size-auto-with-small-source.component.ts(145,9): error TS2322: Type 'ListViewLoadOnDemandMode' is not assignable to type 'string'.
app/examples/load-on-demand/fixed-size-auto/listview-fixed-size-auto.component.ts(4,45): error TS2305: Module '"/Users/NRMac/Projects/nativescript-ui-samples-angular/listview/node_modules/nativescript-ui-listview/index"' has no exported member 'LoadOnDemandListViewEventData'.
app/examples/load-on-demand/fixed-size-auto/listview-fixed-size-auto.component.ts(53,13): error TS2554: Expected 0 arguments, but got 1.
app/examples/load-on-demand/fixed-size-manual/listview-fixed-size-manual.component.ts(4,45): error TS2305: Module '"/Users/NRMac/Projects/nativescript-ui-samples-angular/listview/node_modules/nativescript-ui-listview/index"' has no exported member 'LoadOnDemandListViewEventData'.
app/examples/load-on-demand/fixed-size-manual/listview-fixed-size-manual.component.ts(53,13): error TS2554: Expected 0 arguments, but got 1.
13:48:15 - Compilation complete. Watching for file changes.
Executing before-watch hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/before-watch/nativescript-dev-webpack.js
Executing before-shouldPrepare hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/before-shouldPrepare/nativescript-dev-webpack.js
Skipping prepare.
Unable to apply changes on device: f61895dc. Error is: Socket connection timeouted..
Executing after-watch hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/after-watch/nativescript-dev-typescript.js
Stopping tsc watch

```
`tns run ios` also throws an error log as below

```
Successfully synced application org.nativescript.demoangular on device 
CONSOLE LOG file:///app/tns_modules/@angular/core/bundles/core.umd.js:3130:24: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating '_v.context.item.title')
CONSOLE ERROR [native code]: ERROR CONTEXT {
"view": {
"def": {
"nodeFlags": 1,
"rootNodeFlags": 1,
"nodeMatchedQueries": 0,
"flags": 0,
"nodes": [
{
"nodeIndex": 0,
"parent": null,
"renderParent": null,
"bindingIndex": 0,
"outputIndex": 0,
"checkIndex": 0,
"flags": 1,
"childFlags": 1,
"directChildFlags": 1,
"childMatchedQueries": 0,
"matchedQueries": {},
"matchedQueryIds": 0,
"references": {},
"ngContentIndex": null,
"childCount": 2,
"bindings": [],
"bindingFlags": 0,
"outputs": [],
"element": {
"ns": "",
"name": "StackLayout",
"attrs": [
[
"",
"class",
"itemStackLayout"
]
],
"template": null,
"componentProvider": null,
<…>

```

**Comment by tsonevn** [comment]
Hi @anuragd7,
I followed the steps that you have provided, however, was unable to recreate the case. Can you tell us if this issue happens with a specific example? Also, I notice that [nativescript-ui-samples-angular](https://github.com/telerik/nativescript-ui-samples-angular) using some old NativeScript dependancies. Try to [update](https://docs.nativescript.org/releases/upgrade-instructions) them and check if you will face the same issue. I will update also the dependencies in the repository to the latest ones.

**Comment by anuragd7** [comment]
Hi @tsonevn 
Thanks for your suggestion. I ran tns update in the listview folder and then tried `tns run android` and now encountered the following error log:

 tns run android
```
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-liveSync hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/before-liveSync/nativescript-angular-sync.js
Executing before-watchPatterns hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/before-watchPatterns/nativescript-dev-typescript.js
Executing before-watchPatterns hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/before-watchPatterns/nativescript-dev-webpack.js
Executing before-watch hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.8.4
Executing before-watch hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/before-watch/nativescript-dev-webpack.js
Executing before-shouldPrepare hook from /Users/NRMac/Projects/nativescript-ui-samples-angular/listview/hooks/before-shouldPrepare/nativescript-dev-webpack.js
Skipping prepare.
Refreshing application...
Successfully synced application org.nativescript.demoangular on device f61895dc.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
System.err: android.content.res.Resources$NotFoundException: Resource ID #0xfffffff6
System.err: 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
System.err: 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2167)
System.err: 	at android.content.res.Resources.getAnimation(Resources.java:1192)
System.err: 	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:137)
System.err: 	at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1102)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1600)
System.err: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641)
System.err: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
System.err: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
System.err: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
System.err: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
System.err: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

Additionally have tried to remove platforms, hooks and node-modules to try to fix the above error but still continue to get the same error log.

**Comment by anuragd7** [comment]
Can confirm that on `IOS` the project is running correctly after the `tns update`

**Comment by tsonevn** [comment]
HI @anuragd7,
We have just updated the examples. Can you clone the repository again and check if you will face the same problem? 

Also, make sure that you have installed  Android build-tools 28 on your machine.
