### ISSUE TITLE
Hidden property does only work with explicit TKPropertyEditor

### ISSUE THREAD

**Issue by stefan-kolb** [telerik/nativescript-ui-feedback#949]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
Yes

### Tell us about the problem

Applying the `hidden` property does only work with explicit TKPropertyEditor.

### Which platform(s) does your issue occur on?
Only tested on Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** 3.8.0
- **CLI:** 5.0.0
- **Cross-platform modules:** 5.0.2
- **Runtime(s):** 5.0.0

### Please tell us how to recreate the issue in as much detail as possible.
When configuring the form, properties can be set without an explicit TKProeprtyEditor and will result in the appropriate type, e.g., text for strings.

```xml
<TKEntityProperty tkDataFormProperty name="name" displayName="Name" index="0"></TKEntityProperty>
```

However, if we want to hide the field via `hidden="true"` the app crashes with:
```xml
            <TKEntityProperty tkDataFormProperty name="imageUrl" hidden="true">
            </TKEntityProperty>
```

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onCreateView failed

TypeError: Cannot read property 'parent' of undefined
File: "file:///data/data/io.lion5.Bonista/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js, line: 636, column: 69

StackTrace: 
	Frame: function:'RadDataForm._syncEditorsWithNativeEditors', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 636, column: 70
	Frame: function:'RadDataForm.reload', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 545, column: 22
	Frame: function:'RadDataForm._updateSource', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 194, column: 14
	Frame: function:'RadDataForm.createNativeView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/nativescript-ui-dataform/ui-dataform.js', line: 102, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 491, column: 31
	Frame: function:'', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
	Frame: function:'', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
	Frame: function:'', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19
	Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
	Frame: function:'', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 19
	Frame: function:'ContentView.eachChildView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
	Frame: function:'PageBase.eachChildView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
	Frame: function:'ViewCommon.eachChild', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 868, column: 14
	Frame: function:'ViewBase._setupUI', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 532, column: 14
	Frame: function:'ViewBase._addViewCore', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
	Frame: function:'ViewBase._addView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 642, column: 19
	Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/io.lion5.Bonista/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
	at com.tns.Runtime.callJSMethod(Runtime.java:983)
	at com.tns.Runtime.callJSMethod(Runtime.java:967)
	at com.tns.Runtime.callJSMethod(Runtime.java:959)
	at com.tns.FragmentClass.onCreateView(FragmentClass.java:45)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

````

__Adding an explicit TKPropertyEditor fixes the problem.__

```xml
            <TKEntityProperty tkDataFormProperty name="imageUrl" hidden="true">
                <TKPropertyEditor tkEntityPropertyEditor type="Text"></TKPropertyEditor>
            </TKEntityProperty>
```

**Comment by tgpetrov** [comment]
Hi @stefan-kolb 
Thank you for your report.
I will close this issue since we also have it logged [here](https://github.com/telerik/nativescript-ui-feedback/issues/1011).
