### ISSUE TITLE
RadListView itemTap args.view undefined after master/detail navigation (Android only)

### ISSUE THREAD

**Issue by manoldonev** [telerik/nativescript-ui-feedback#976]
### Tell us about the problem
RadListView itemTap args.view is undefined in a specific [master/detail scenario](https://github.com/NativeScript/template-master-detail-ts) when tapping on an item after master/detail navigation has been executed (i.e. navigate forward and back to the master listview).

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- **nativescript-ui-listview:** 5.0.1
- **CLI:** 5.1.0
- **Cross-platform modules:** 5.1.1
- **Runtime(s):** 5.1.0

### Please tell us how to recreate the issue in as much detail as possible.
1. `tns create md1 --template tns-template-master-detail-ts`
2. `cd md1`
3. `tns run android`
4. Tap first item -- navigates to car detail screen
5. Go back (via arrow or hardware button)
6. Try to tap the first item again -- app crashes with exception:
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onItemClick failed

TypeError: Cannot read property 'bindingContext' of undefined
File: "file:///data/data/org.nativescript.MasterDetail/files/app/cars/cars-list-page.js, line: 24, column: 34

StackTrace: 
	Frame: function:'onCarItemTap', file:'file:///data/data/org.nativescript.MasterDetail/files/app/cars/cars-list-page.js', line: 24, column: 35
	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.MasterDetail/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
	Frame: function:'onItemClick', file:'file:///data/data/org.nativescript.MasterDetail/files/app/tns_modules/nativescript-ui-listview/ui-listview.js', line: 583, column: 32

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
	at com.tns.Runtime.callJSMethod(Runtime.java:987)
	at com.tns.Runtime.callJSMethod(Runtime.java:967)
	at com.tns.Runtime.callJSMethod(Runtime.java:959)
	at com.tns.gen.com.telerik.widget.list.RadListView_ItemClickListener.onItemClick(RadListView_ItemClickListener.java:17)
	at com.telerik.widget.list.RadListView.notifyOnTapUp(RadListView.java:723)
	at com.telerik.widget.list.ListViewGestureListener.onTapUp(ListViewGestureListener.java:175)
	at com.telerik.widget.list.ListViewGestureListener.onSingleTapUp(ListViewGestureListener.java:274)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
	at com.telerik.widget.list.ListViewGestureListener.onTouchEvent(ListViewGestureListener.java:149)
	at com.telerik.widget.list.RadListView.onTouchEvent(RadListView.java:544)
	at android.view.View.dispatchTouchEvent(View.java:9294)
```

Here is the `onCarItemTap` implementation:
``` ts
export function onCarItemTap(args: ListViewEventData): void {
    const tappedCarItem = <Car>args.view.bindingContext; // <-- args.view is undefined

    topmost().navigate({
        moduleName: "cars/car-detail-page/car-detail-page",
        context: tappedCarItem,
        animated: true,
        transition: {
            name: "slide",
            duration: 200,
            curve: "ease"
        }
    });
}
```

**Comment by manoldonev** [comment]
Note that upon back navigation the scenario in the template actually rebinds the RadListView to a new ObservableArray.

**Comment by manoldonev** [comment]
Closing this as I managed to [rework the unsubscribe-from-data-changes logic](https://github.com/NativeScript/template-master-detail-ts/pull/110) in the templates  that caused the RadListView to rebind on back navigation (and ultimately triggered this problem).

**Comment by Omi231** [comment]
@manoldonev  how to unsubscribe from data changes explicitly? can u tell me how to do that?
