### ISSUE TITLE
nativescript-ui-listview 5.1.0 and 5.1.1

### ISSUE THREAD

**Issue by nuvoPoint** [telerik/nativescript-ui-feedback#999]
### Did you verify this is a real problem by searching the [NativeScript Forum](https://discourse.nativescript.org/)?
_Yes/No_

THIS IS NO LONGER RELEVANT, PLEASE REMOVE THIS SECTION!

### Tell us about the problem
Can't build after updating from nativescript-ui-listview 5.0.1 to versions 5.1.0 and 5.1.1.

The error is:
Exception in thread "main" java.lang.ClassNotFoundException: Class: com.telerik.android.data.ListViewGroupFunction

### Which platform(s) does your issue occur on?
Only testet this on Android

### Please provide the following version numbers that your issue occurs with:
- **Progress NativeScript UI version:** nativescript-ui-listview 5.1.0 and 5.1.1
- **CLI:** 5.1.1
- **Cross-platform modules:** 5.1.2
- **Runtime(s):** tns-android: 5.1.0

**Comment by tsonevn** [comment]
Hi @nuvoPoint,
Can you send us a sample project, where the issue can be reproduced?

**Comment by elena-p** [comment]
closing due to inactivity

**Comment by LeongKH** [comment]
Hi all, 
I am facing similar issue with following error message.
It is able to preview on iOS, but unable to do so on android
I have provided source file as well as package-json, package lock-json for more information.

Exception in thread "main" java.lang.ClassNotFoundException: Class: com.telerik.android.data.ListViewGroupFunction
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:785)
        at org.nativescript.staticbindinggenerator.Generator.collectInterfaceMethods(Generator.java:710)
        at org.nativescript.staticbindinggenerator.Generator.getPublicApi(Generator.java:228)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:342)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:134)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:173)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:91)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:67)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:47)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runSbg'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Please provide the following version numbers that your issue occurs with:**
Progress NativeScript UI version: nativescript-ui-listview 6.0.0
CLI: 5.2.4
android build-tools;28.0.3
android emulator 28.0.23
Android SDK Platform 28
system-images;android-28;google_apis;x86 |
[Package-json.zip](https://github.com/telerik/nativescript-ui-feedback/files/2998947/Package-json.zip)
[src.zip](https://github.com/telerik/nativescript-ui-feedback/files/2998948/src.zip)
